# Generated by Django 3.1.7 on 2021-09-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'درس ها'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'ثبت نام', 'verbose_name_plural': 'ثبت نام ها'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانش آموز', 'verbose_name_plural': 'دانش آموزان'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'ترم', 'verbose_name_plural': 'ترم ها'},
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
